name: 'Nightly Delete All Azure resources'

on:
  schedule:
  - cron:  "0 23 * * *"
  workflow_dispatch:
 
jobs:
  delete-azure-resources:
    name: 'Azure'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: production
 
    permissions:
      id-token: write
      contents: read
 
    defaults:
      run:
        shell: bash
 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
 
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
 
      - name: Set Azure Subscription
        run: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
 
      - name: Set Azure Environment Variables
        run: |
          echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
      
      - name: Get all resource groups for RESOURCE_GROUP_NAME
        id: get_resource_groups
        run: |
          RESOURCE_GROUP_NAME="${{ secrets.RESOURCE_GROUP_NAME }}"
          RESOURCE_GROUPS=$(az group list --query "[?starts_with(name, '$RESOURCE_GROUP_NAME')].name" -o json)
          # Convert JSON array to a comma-separated list
          RESOURCE_GROUPS_LIST=$(echo "$RESOURCE_GROUPS" | jq -r '.[]' | paste -sd "," -)
          echo "RESOURCE_GROUPS=$RESOURCE_GROUPS_LIST" >> $GITHUB_ENV
        
      - name: Output Resource Groups
        run: echo "Resource Groups:${{ env.RESOURCE_GROUPS }}"
        
      - name: Delete Resource Groups
        run: |
          IFS=','  # Set comma as the delimiter
          for rg in $RESOURCE_GROUPS; do
            echo "Deleting resource group: $rg"
            az group delete --name "$rg" --yes --no-wait
          done

    # Fetch and Delete App Registrations with Display Names starting with RESOURCE_GROUP_NAME
      - name: Get all App Registrations for RESOURCE_GROUP_NAME
        id: get_app_registrations
        run: |
          RESOURCE_GROUP_NAME="${{ secrets.RESOURCE_GROUP_NAME }}"
          # Fetch all app registrations that have display names starting with RESOURCE_GROUP_NAME
          APP_REGISTRATIONS=$(az ad app list --filter "startswith(displayName,'$RESOURCE_GROUP_NAME')" --query "[].appId" -o json)
          # Convert JSON array to a comma-separated list
          APP_REGISTRATIONS_LIST=$(echo "$APP_REGISTRATIONS" | jq -r '.[]' | paste -sd "," -)
          echo "APP_REGISTRATIONS=$APP_REGISTRATIONS_LIST" >> $GITHUB_ENV
  
      - name: Output App Registrations
        run: echo "App Registrations:${{ env.APP_REGISTRATIONS }}"
  
      - name: Delete App Registrations
        run: |
          IFS=','  # Set comma as the delimiter
          for app_id in $APP_REGISTRATIONS; do
            echo "Deleting app registration with App ID: $app_id"
            az ad app delete --id "$app_id"
          done 
