# This workflow installs the latest version of Terraform CLI and configures the the Azure command line with credentials and the subscription details. On pull request events, this workflow will run
# `terraform init`, `terraform fmt`, and `terraform plan` (speculative plan via Terraform Cloud). On push events
# to the "main" branch, `terraform apply` will be executed.
 
name: 'registration delete'
 
on:
 workflow_dispatch:
   inputs:
     resource_group_number:
       required: true
       default: '001'
       description: Please select the resource group you want to delete
       type: choice
       options:
         - '001'
         - '002'
         - '003'
 
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: production
 
    permissions:
      id-token: write
      contents: read
 
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
 
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4
 
    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
        
    # Log into Azure and set the subscription
    - name: Azure Login
      uses: azure/login@v2
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
 
    - name: Set Azure Subscription
      run: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - name: Set Azure Environment Variables
      run: |
        echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
        echo "ARM_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}" >> $GITHUB_ENV
        echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
        echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
        echo "TF_VAR_subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
    
 
    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init
      working-directory: ./ops
 
    - name: Import Resource Group
      run: terraform import azurerm_resource_group.rg /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.RESOURCE_GROUP_NAME }}'-'${{ github.event.inputs.resource_group_number }}
      working-directory: ./ops
   
    - name: Delete specific app registration
      run: az ad app delete --id $(az bot show --resource-group ${{ secrets.RESOURCE_GROUP_NAME }}'-'${{ github.event.inputs.resource_group_number }} --name ${{ secrets.RESOURCE_GROUP_NAME }}'-'${{ github.event.inputs.resource_group_number }} --query "properties.msaAppId" -o tsv)

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
      working-directory: ./ops
