name: 'Nightly Delete Azure resources'

on:
  schedule:
    - cron: "30 10 * * *"
  workflow_dispatch:
 
jobs:
  delete-azure-resources:
    name: 'Azure'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: production
 
    permissions:
      id-token: write
      contents: read
 
    defaults:
      run:
        shell: bash
 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
 
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
 
      - name: Set Azure Subscription
        run: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
 
      - name: Set Azure Environment Variables
        run: |
          echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
      
      - name: Get all resource groups for RESOURCE_GROUP_NAME
        id: get_resource_groups
        run: |
          RESOURCE_GROUPS=$(az group list --query "[?starts_with(name, 'TerraformOCB')].name" -o json)
          # Convert JSON array to a comma-separated list
          RESOURCE_GROUPS_LIST=$(echo "$RESOURCE_GROUPS" | jq -r '.[]' | paste -sd "," -)
          echo "RESOURCE_GROUPS=$RESOURCE_GROUPS_LIST" >> $GITHUB_ENV
        
      - name: Output Resource Groups
        run: echo "Resource Groups:${{ env.RESOURCE_GROUPS }}"
        
      - name: Delete Resource Groups
        run: |
          IFS=','  # Set comma as the delimiter
          for rg in $RESOURCE_GROUPS; do
            echo "Deleting resource group: $rg"
            az group delete --name "$rg" --yes --no-wait
          done 
 
